objects/DuplicatedUsersBatch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for  DuplicatedUsersBatch job. - Hours is used to set the createdDate limit in the query. - StringForTimeInterval sets the interval to fire the job</description>
    <fields>
        <fullName>BatchSize__c</fullName>
        <label>Batch Size</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobName__c</fullName>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StringForTimeInterval__c</fullName>
        <label>String For TimeInterval</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DuplicatedUsersBatch_Settings</label>
</CustomObject>

objects/ExceptionLog__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <label>Exception Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionDescription__c</fullName>
        <label>Exception Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionDetails__c</fullName>
        <label>Exception Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <label>Exception Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DuplicatedPeople_Schedulable_Test.cls
@isTest
private class DuplicatedPeople_Schedulable_Test {

	@isTest
	private static void testSchedulerMethod() {

		Test.startTest();
		Id jobId = DuplicatedPeople_Schedulable.SchedulerMethod();
		Test.stopTest();

		List<CronTrigger> cTrigger = [SELECT Id, CronExpression
		                        FROM CronTrigger];

		DuplicatedUsersBatch_Settings__c settingsBatch = DuplicatedUsersBatch_Settings__c.getOrgDefaults();
		
		System.assertEquals(1, cTrigger.size());
		System.assertEquals(jobId, cTrigger.get(0).Id);
		System.assertEquals(settingsBatch.StringForTimeInterval__c, cTrigger.get(0).CronExpression);
	}

	@isTest
	private static void ifSchedulerMethodIsColledMoreThanOnce_itShouldScheduleOnlyOneJob() {

		Test.startTest();
		Id firstJobId = DuplicatedPeople_Schedulable.SchedulerMethod();
		Id secondJobId = DuplicatedPeople_Schedulable.SchedulerMethod();
		Test.stopTest();

		List<CronTrigger> cTrigger = [SELECT Id, CronExpression
		                        FROM CronTrigger];
		
		System.assertEquals(1, cTrigger.size());
		System.assertEquals(firstJobId, cTrigger.get(0).Id);
	}

	@isTest
	private static void testExceptionHandling() {
		//============================= Set Data Test ==================================
		DuplicatedUsersBatch_Settings__c batchSettings = DuplicatedUsersBatch_Settings__c.getOrgDefaults();
		batchSettings.StringForTimeInterval__c = 'Fail cron expression';
		Database.update(batchSettings);
		//============================= End Data Test ==================================

		Test.startTest();
		Id jobId = DuplicatedPeople_Schedulable.SchedulerMethod();
		Test.stopTest();

		List<ExceptionLog__c> exLogs = [SELECT ClassName__c, MethodName__c, ExceptionDetails__c,
										ExceptionCode__c, ExceptionDescription__c, ExceptionType__c
		                                FROM ExceptionLog__c];

		System.assertEquals(1, exLogs.size());
	}

	//===================================================================================

	@testSetup
	static void setTestData() {
		DuplicatedUsersBatch_Settings__c batchSettings;
		batchSettings = new DuplicatedUsersBatch_Settings__c();
		batchSettings.Hours__c = 25;
		batchSettings.JobName__c = 'Duplicated People';
		batchSettings.StringForTimeInterval__c = '0 0 0 ? * *';
		batchSettings.BatchSize__c = 200;
		Database.insert(batchSettings);
	}
}