objects/People__c.object
<CustomObject>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <label>Employment_Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>People</label>
    <nameField>
        <label>Nombre de persona</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peoples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Build.cls
public class Build  {
	//==========================================================================
	// PeopleBuilder
	//==========================================================================

	public class PeopleBuilder {
		private People__c obj = new People__c();

		public PeopleBuilder withName(String val) {
			obj.Name = val;
			return this;
		}

		public PeopleBuilder withEmploymentStatus(String val) {
			obj.Employment_Status__c = val;
			return this;
		}

		public People__c build() {
			return obj;
		}
	}

	public static PeopleBuilder createPeople() { return new PeopleBuilder(); }

}